### ISSUE TITLE
Uglify throwing error in production build 

### ISSUE THREAD

**Issue by usopan** [rangle/redux-gtm#30]
ERROR in main_10eaba819d1af1f76070.js from UglifyJs
SyntaxError: Name expected [./~/redux-gtm/lib/get-data-layer.js:1,0] 

I am using webpack to build client and server js separately then it uglifies frontend js using webpack uglifyjs  plugin.

**Comment by ttmarek** [comment]
Hi @usopan. Are you transpiling your code through babel before minimizing it?

**Comment by usopan** [comment]
I suppose not as I am excluding node_modules from bable loader.
`const path = require('path')
const webpack = require('webpack')
const AssetsPlugin = require('assets-webpack-plugin')

const CONFIG = require('./webpack.base')
const {CLIENT_ENTRY, CLIENT_OUTPUT, PUBLIC_PATH} = CONFIG

module.exports = {
  devtool: false,
  entry: {
    main: [CLIENT_ENTRY],
    vendor: [
      'react',
      'react-dom',
      'react-router',
      'redux',
      'react-redux',
      'aphrodite'
    ],
  },
  output: {
    filename: '[name]_[chunkhash].js',
    chunkFilename: '[name]_[chunkhash].js',
    publicPath: PUBLIC_PATH,
    path: CLIENT_OUTPUT
  },
  plugins: [
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': '"production"',
      '__DEV__': false
    }),
    new webpack.optimize.OccurrenceOrderPlugin(),
    new webpack.optimize.AggressiveMergingPlugin(),
    new webpack.optimize.CommonsChunkPlugin('vendor', 'vendor_[hash].js', 2),
    new AssetsPlugin({
      filename: 'assets.json'
    }),
    new webpack.optimize.DedupePlugin(),
    new webpack.optimize.UglifyJsPlugin({
      compressor: {
        screw_ie8: true,
        warnings: false
      },
      mangle: {
        screw_ie8: true
      },
      output: {
        comments: false,
        screw_ie8: true
      }
    }),
    new webpack.NoErrorsPlugin(),
    new webpack.IgnorePlugin(/locale/, /moment$/)
  ],
  module: {
    loaders: [
      {
        test: /\.js$/,
        loader: 'babel',
        query: {
          cacheDirectory: true,
          presets: ["es2015", "react", "stage-0", "react-optimize"],
        },
        exclude: /node_modules/
      },
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loader: 'babel-loader',

        query: {
          presets: ['es2015', 'react']
        }
      }
    ]
  },
  node: {
    net: 'empty',
    tls: 'empty',
    dns: 'empty'
  },
  resolve: {
    packageAlias: 'browser'
  }
}
`

**Comment by ttmarek** [comment]
@usopan I've released a new version that should fix the issue you're having. Could you run `npm update redux-gtm` and check to see if the error persists?

**Comment by usopan** [comment]
Works like a charm thanks from our Team.

**Comment by ttmarek** [comment]
@usopan glad to hear it! Thanks for using redux-gtm and taking the time to open up an issue. The library is still very young, and growing. Feel free to open up any more issues, or even submit a PR if you've got any ideas for improvement.
