### ISSUE TITLE
getDataLayer is not defined

### ISSUE THREAD

**Issue by dcifuen** [rangle/redux-gtm#37]
After adding the Google Tag Manager container snippet and following the installation instructions as documented I'm getting this message in the console:

get-data-layer.js?d368:15Uncaught ReferenceError: getDataLayer is not defined

Is there something I'm missing in how I should load the dependency?

**Comment by ttmarek** [comment]
Hi @dcifuen, I'm not completely sure why you're getting this error, although I suspect it may be an ES2015/ES6 issue that I solved earlier. If possible, could you update `redux-gtm` to the latest version `0.2.2` (just released a few minutes ago), and let me know if you still get an error?

**Comment by dcifuen** [comment]
@ttmarek I updated and it now works! and yes, I was using ES6. Thanks a lot

**Comment by ttmarek** [comment]
No problem @dcifuen. Thanks for trying out redux-gtm and taking the time to submit an issue. The library is still young and growing. Please feel free to make any more issues or open up a PR if you've got any ideas for improvement.
