### ISSUE TITLE
AoT Compatibility 

### ISSUE THREAD

**Issue by watrool** [rangle/redux-gtm#39]
The calling of `createMetaReducer` is prohibited by AoT with error message:
```
Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol lightningStore in /Users/newAccount/Desktop/.../src/app/store.ts, resolving symbol imports in /Users/newAccount/Desktop/.../src/app/imports.ts, resolving symbol LightningAppModule in /Users/newAccount/Desktop/.../src/app/lightning-app.module.ts, resolving symbol LightningAppModule in /Users/newAccount/Desktop/.../src/app/lightning-app.module.ts
```

**Comment by bennett000** [comment]
- I wonder if changing the arrow function here to a named `function` might help: https://github.com/rangle/redux-gtm/blob/master/src/create-meta-reducer.js#L5

- I also wonder in general if top level function exports work with ES6 modules
- I also wonder if top level function exports work with CommonJS modules

@watrool do we have a sandbox scenario for this?

**Comment by watrool** [comment]
@bennett000 
I tried change the arrow function and it does not work (although `arrow-function-exports` is indeed an AoT dont). 

For the exports, I tried to import `createMetaReducer` from `create-meta-reducer.js` directly not through the top level exports, but still does not work.

My idea is that the problem is the `nested-function` case in the sandbox (mainly because i cannot find a solution for that).

**Comment by bennett000** [comment]
@watrool I fear it's got to be a static method:

```js
export class MyPointlessContainerClass {
  static myMethodWhichShouldReallyJustBeAPureFunction() {
    // do stuff
  }
  static myOtherMethodWhichShouldBeAFunction() {
    // do stuff
  }
}
```

**Comment by ttmarek** [comment]
The AoT compiler seems to have an issue with all meta reducers in general. I ran into the same problem with [ngrx-store-logger](https://github.com/btroncone/ngrx-store-logger), and created an issue [here](https://github.com/btroncone/ngrx-store-logger/issues/13). From a `redux-gtm` standpoint there isn't much that can be done.

**Comment by watrool** [comment]
@ttmarek According to the link I found from your issue, I managed to let `ngrx-store-logger` with `compose` become AoT-friendly. Please checkout the new `ngrx-compose` case in the sandbox.

So if the issue related to `redux-gtm` is only this `compose` function, maybe we can find a way around it.

**Comment by ttmarek** [comment]
The solution here was to wrap the exported meta reducer in another meta reducer that was defined as a function declaration before exporting it.

```js
import { createMetaReducer } from 'redux-gtm';
import { eventDefinitions } from './somewhere';
import { someOtherReducer } from './somewhere-else';

const gtmReducer = createMetaReducer(eventDefinitions);

// wrap whatever other reducers you've got in the meta reducer
const finalReducer = gtmReducer(someOtherReducer);

export function reducer(state: any, action: any) {
   return finalReducer(state, action);
}
```
